.Dd aug/2024
.Dt HWL 1
.Os 
.Sh NAME
.Nm hwl
.Nd histogram of word lengths.
.Sh SYNOPSIS
.Nm hwl
.Op Fl d
.Op Fl o Ar output_file
.Op Fl c Ar num_columns_output
.Op Fl s Ar repeating_string
.Sh DESCRIPTION
The
.Nm
command reads a text file, identifies words (as sequences of
alphabetic characters) and prints an histogram of word lengths
to
.Ar stdout
or the
.fl o
option specified file.
.Sh OPTIONS
.Bl -tag
.It FL d
This flag activates a debug mode that prints all words as they
are recognized.  The debug info is output to
.Ar stdout
despite on specifying the
.Fl o
option.
.Pp
This allows to sort the output numerically and check that the
number of words matches the corresponding row in the histogram.
.It Fl c Ar num_columns_output
The
.Nm
command determines the number of columns to set the maximum
histogram from the output device (or a default of
.Ar DEFAULT_COLUMNS )
in case the output is redirected to a device (or a pipe).
You can specify a number of columns if you need to narrow
the output or the output width is not detectable from the
system.
.It Fl o Ar output_file
This option allows to specify the output file to dump the
histogram to.
.It Fl s Ar repeating_string
The string passed as argument is repeated to make the columns
that conform the bars of the histogram.
.El
.Sh EXAMPLES
The following is produced when
.Nm
is run against its source file
.Bd -literal
$ hwl -c 40 hwl.c
[hwl.c]
 1: ........................... <74>
 2: ................... <53>
 3: ............................... <86>
 4: ............................................. <124>
 5: ................... <52>
 6: ................. <47>
 7: .............. <39>
 8: ........ <23>
 9: ... <7>
10: . <2>
$ _
.Ed
.Sh AUTHORS
.An "Luis Colorado" Aq luiscoloradourcola@gmail.com .
.Pp
This program was inspired on ``The C programming language''
of Brian Kernighan and Dennis Ritchie.
It appears there as an exercise (Ex 1-13 on page 24 of second
edition)
